import React from "react";
import Topbar from "./Topbar";
import Banner from "./Banner"
import Footer from "./Footer";
import { Roboto } from "@next/font/google";
import Head from 'next/head'


const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});
const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>Pets Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/pet-removebg-preview.ico" />
      </Head>
      {/* <Topbar /> */}
      <div className={roboto.className}> {children} </div>
      <Footer/>
    </>
  );
};

export default Layout;
