import Head from 'next/head'
import { Inter } from '@next/font/google'

import Grid from '@mui/material/Grid'; 

import React, { Component } from 'react'
import axios from 'axios'

export default function Home() {
  
  return (
    
    <div>
      <Head>
        <title>Company</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>



    </div>
  )
}